require_relative '../../common'

sample '001.hand'
sample '002.hand'
sample '003.hand'

test "001.hand"
test "002.hand"
test "003.hand"
test "004.hand"
test "005.hand"
test "006.hand"
test :random, "?", 100, 10
test :random, "?", 100, 10
test :random, "?", 100, 10
test :random, "?", 100, 10
test :random, "?", 100, 10
test :random, "?", 100, 10
test :random, "?", 100, 10
test :random, "?", 100, 10
test :random, "?", 100, 10
test :random, "?", 100, 10
test :random, "?", 1000, 100
test :random, "?", 1000, 100
test :random, "?", 1000, 100
test :random, "?", 1000, 100
test :random, "?", 1000, 100
test :random, "?", 1000, 100
test :random, "?", 1000, 100
test :random, "?", 1000, 100
test :random, "?", 1000, 100
test :random, "?", 1000, 100
