require_relative '../../common'

sample '001.hand'
sample '002.hand'

test "001.hand"
test "002.hand"
test :random, 4
test :random, 4
test :random, 4
test :random, 4
test :random, 4
test :random, 4
test :random, 4
test :random, 4
test :random, 4
test :random, 4
test :random, 1000
test :random, 1000
test :random, 1000
test :random, 1000
test :random, 1000
test :random, 1000
test :random, 1000
test :random, 1000
test :random, 1000
test :random, 1000
test :random, 100000
test :random, 100000
test :random, 100000
test :random, 100000
test :random, 100000
test :random, 100000
test :random, 100000
test :random, 100000
test :random, 100000
test :random, 100000
