require_relative '../../common'

sample '001.hand'
sample '002.hand'

test "001.hand"
test "002.hand"
test "003.hand"
test :random, "?", 50, 50
test :random, "?", 50, 50
test :random, "?", 50, 50
test :random, "?", 50, 50
test :random, "?", 50, 50
test :random, "?", 50, 50
test :random, "?", 50, 50
test :random, "?", 50, 50
test :random, "?", 50, 50
test :random, "?", 50, 50
test :random_no, "?", 50, 50
test :random_no, "?", 50, 50
test :random_no, "?", 50, 50
test :random_no, "?", 50, 50
test :random_no, "?", 50, 50
test :random_no, "?", 50, 50
test :random_no, "?", 50, 50
test :random_no, "?", 50, 50
test :random_no, "?", 50, 50
test :random_no, "?", 50, 50
