require_relative '../../common'

sample '001.hand'

multitest *[
  [:random, 10**4, -100, -100],
  [:random, 1000, -1000, -1000],
  [:random, 10, -10**5, -10**5],
  [:random, 1, 10**6, 2],
  [:random, 1, 10**6, 10**6],
]
